Repository akhildhiman7/AlgoHacktoberFest, pull requests merged in 2022-10, with the labels that each got.

#2 Sorting Algorithm
  Sorting Algorithm.c
Labels: hacktoberfest-accepted

#3 Added linked list reversal
  reverseLinkedList.java
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#4 added bianry search
  binarysearch.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#5 added course scheduling
  scheduling.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#6 bubbel-sort
  bubblesort.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7 added odd linkedList
  oddEvenLinkedList.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#9 juggling letters
  juggling_letters
Labels: hacktoberfest, hacktoberfest-accepted

#10 added flood fill
  floodFill.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#11 anagram-solver
  anagram_solver.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#12 MatrixAddition.c
  MatrixAddition.c
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#15 add add_two_matrices.cpp
  add_two_matrices.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#14 Added number of Island java program
  number_of_islands.java
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
